<a href="https://colab.research.google.com/github/kaanakgundogdu/tensorflow_notes/blob/main/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensors

In [3]:
import tensorflow as tf

print(tf.__version__)

2.11.0


### Scalar: a single number

In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.ndim

0

### Vector: a number with direction

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

### Matriix: a 2 dimensional array of numbers

In [12]:
matrix=tf.constant([[25,50],
                   [99,33]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 50],
       [99, 33]], dtype=int32)>

In [13]:
matrix.ndim

2

In [17]:
float_matrix=tf.constant([[1.,2.],
                          [3.,4.],
                          [5.,6.]],dtype=tf.float16)
float_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [18]:
float_matrix.ndim

2

### Tensor: an n dimensional array of numbers.

In [20]:
tensor = tf.constant( [[[1,2,3],
                        [4,5,6]],
                       
                        [[7,8,9],
                         [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]                      
                        ]
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [23]:
tensor.ndim

3

### Create tensor with tf.Variable()

In [26]:
changeable_tensor=tf.Variable([3,99])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 3, 99], dtype=int32)>

In [30]:
# this gives error
#changeable_tensor[0]=2
changeable_tensor[0].assign(77)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([77, 99], dtype=int32)>

### Creating Random Tensors

In [34]:
random_1= tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,4))
random_2= tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,4))
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>, <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)

### Shuffle the order of elements in a tensor

In [42]:
not_shuffled=tf.constant([[44,55,88],
                          [22,11,33],
                          [99,66,14]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 11, 33],
       [44, 55, 88],
       [99, 66, 14]], dtype=int32)>

In [50]:
# add seed and gives same order again and again
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 55, 88],
       [22, 11, 33],
       [99, 66, 14]], dtype=int32)>

In [51]:
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 55, 88],
       [22, 11, 33],
       [99, 66, 14]], dtype=int32)>

### Create tensors with numpy and all ones,zeros

In [53]:
tf.ones([5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [55]:
tf.zeros(shape=(9,9))

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [59]:
import numpy as np
numpy_A=np.arange(1,21,dtype=np.int32)
numpy_A
# X = tf.constant(somematrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int32)

In [68]:
A=tf.constant(numpy_A,shape=(2,5,2))
B=tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]],
 
        [[11, 12],
         [13, 14],
         [15, 16],
         [17, 18],
         [19, 20]]], dtype=int32)>,
 <tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20], dtype=int32)>)

In [72]:
A.ndim , B.ndim

(3, 1)

### Getting information from tensors

 * Shape 
 * Rank
 * Axis or dimension
 * Size

In [74]:
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [76]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [84]:
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimensions(rank): ",rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])
print("Elements along the last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in tensor(tf format): ",tf.size(rank_4_tensor))
print("Total number of elements in tensor(numpy format): ",tf.size(rank_4_tensor).numpy())


Datatype of every element:  <dtype: 'float32'>
Number of dimensions(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in tensor(tf format):  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor(numpy format):  120


### Indexing tensors

In [87]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [89]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [101]:
print(rank_4_tensor[:1,:1,:1,:1])
print(rank_4_tensor[:1,:1,:1,:])
print(rank_4_tensor[:,:1,:1,:1])
print(rank_4_tensor[:1,:1,:3,:1])

tf.Tensor([[[[0.]]]], shape=(1, 1, 1, 1), dtype=float32)
tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)
tf.Tensor(
[[[[0.]]]


 [[[0.]]]], shape=(2, 1, 1, 1), dtype=float32)
tf.Tensor(
[[[[0.]
   [0.]
   [0.]]]], shape=(1, 1, 3, 1), dtype=float32)


In [105]:

rank_2_tensor=tf.constant([[1,2],
                           [3,4]])
rank_2_tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [107]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [109]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

### Adding extra dimension to a tensor

In [111]:
rank_3_tensor= rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [116]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (aka Tensor operations)

**Basic Operations**

 +, - , / , * 

In [118]:
tensor= tf.constant([[2,4],
                    [6,8]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [120]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [60, 80]], dtype=int32)>

In [122]:
tensor /2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [124]:
tensor -22

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-20, -18],
       [-16, -14]], dtype=int32)>

In [126]:
tf.multiply(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 12],
       [18, 24]], dtype=int32)>

In [131]:
tf.divide(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.4, 0.8],
       [1.2, 1.6]])>

In [132]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

**Matrix multiplication**